### PR TITLE
Automate software list

### PR DESCRIPTION
**Pull request by Bisaloo**
Is it desirable to have all packages from r-universe here or should we include just a subset? Should I use the (more detailed) `Description` field from the `DESCRIPTION` file to introduce each package?

cc @seabbs as the main user of the r-universe.

Preview:

Screen Shot 2022-01-27 at 14 43 08

### CODE REVIEW

**Comment by seabbs** [comment]
Personally would vote for a subset of curated projects (`idbrms` for example is an experiment that isn't seeing much use or dev time). Partly that comes down to finalising what should and shouldn't be in the universe (and when). I'd also perhaps go with the longer descriptions as well as the titles but not a strong opinion.

**Comment by Bisaloo** [comment]
I can also limit to packages from r-universe that are also on CRAN but I don't know if we want to consider that also packages on CRAN are worth showing.

**Comment by seabbs** [comment]
I haven't worked out how to get some of the work I have been doing that I would consider ready for use by others (like `forecast.vocs` and `epinowcast`) on CRAN yet due to the use of `cmdstanr` so that might quite a high barrier to entry (though maybe that is a good thing)?

**Comment by Bisaloo** [comment]
I'll give a go to this option: https://github.com/epiforecasts/universe/commit/7c55a4c418295c9faa59871d3554427efe206cf7. Each r-universe entry will have an additional boolean value in `display_website` to determine whether it should be displayed on the website or not.

@seabbs, no rush but when you have a moment, could you have a look and decide which of your packages should be present on the website?

**Comment by sbfnk** [comment]
That sounds like a great solution, @Bisaloo - agree that CRAN is too restrictive.

**Comment by Bisaloo** [comment]
Is this better? With a full description

Screen Shot 2022-02-01 at 15 03 50-fullpage

**Pull request merged**
