### PR TITLE
Move aside down

### PR DESCRIPTION
**Pull request by sbfnk**
Changes make text appear before tweets on narrow screens.

### CODE REVIEW

**Comment by Bisaloo** [comment]
I tried this first but I think it looks very awkward. What about removing the twitter timeline entirely on narrow screens?

**Comment by sbfnk** [comment]
Yes, that would work I think. Which bit do you think looks awkward?

**Comment by Bisaloo** [comment]
Hmm, strange. I don't know what happened earlier but I just re-tested and this is perfectly fine. Merging now.

**Review by Bisaloo — APPROVED** [review]

**Comment by sbfnk** [comment]
OK - for what it's worth I think aside binds to a paragraph so making sure that the figure and text are all in one paragraph with line breaks through <br> (rather than <p>) was key to making it look reasonable.

**Pull request merged**
