### PR TITLE
Add blog post on robust GitHub Actions

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Review by seabbs — COMMENTED** [review]
Really like this. I got some useful insights from it (exponential retrying on URLs packaged up!). 

I think I would have a sentence or so discussing what GitHub actions are, what we had before (Cron on server), and what we  liked about GA that made us move. I might also add a summary paragraph and perhaps discuss continuing challenges?

**Comment by sbfnk** [comment]
This looks great - really nice writeup which I suspect will be useful for others.

I wasn't sure initially what you meant by "flaky": buggy, or unstable, or not running at all etc. Perhaps have a think about whether there is a better word for the title (there might not be) but definitely clarify what exactly you mean by "were flaky and often failing for spurious reasons" - ideally perhaps in a way that people searching for the same problems using a search engine would be pointed to this solution.

Other potential examples for our Action use might be to download and process weekly LFD testing data in England, although I suspect that data stream is now ending with the end of free LFD testing: https://github.com/epiforecasts/covid19.lfd.england/blob/main/.github/workflows/lfd.yaml
Similarly we used to process local R estimates but are no longer doing so:
https://github.com/epiforecasts/covid19_uk_local/blob/main/.github/workflows/rt.yaml
(PS: is there a way to disable the action whilst retaining the workflow file for transparency?)

For "Notify the whole team when a scheduled workflow fails" and the next header I think they need to go down a level and have a header along the lines of "Improving resilience to github action failures" or something of source that's on the same level as later "sources of ..." to make the structure clearer. It wasn't immediately clear to me when you were stating the problem and when moving on to solutions.

**Comment by seabbs** [comment]
They can be disabled in the actions tab.  It's one of the ... options on the right after you click on a specific action

**Comment by Bisaloo** [comment]
@seabbs 

> I think I would have a sentence or so discussing what GitHub actions are, what
> we had before (Cron on server), and what we liked about GA that made us move.

This is an interesting but different topic, targeted to a different audience
IMO. I didn't want to write a long, general post about what GHA are, their
benefits and their challenges. I wanted a bite-sized post mainly targeted at
people that are already somewhat GHA "power users": they've moved to the stage
of writing their own GitHub Actions but are tired of the constant failures. As a
way to answer (badly) to your comment, I have however added a link to my
presentation on GitHub Actions.

> I might also add a summary paragraph and perhaps discuss continuing
> challenges?

What would you see specifically in 'continuing challenges'? I could see some
things if it was a general post on GitHub Actions (e.g., lack of computing
power, lack of central management options, etc.) but not sure about the specific
topic of flakiness.

**Pull request merged**
